config/routes.rb
Rails.application.routes.draw do
  get 'settings' => 'settings#edit', as: :settings
  post 'settings' => 'settings#update'
  put 'settings' => 'settings#update'
  patch 'settings' => 'settings#update'
  resources :users, only: [:edit, :update, :show]
  resources :posts do
    resources :comments
  end
  root to: 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  mount_uploader :featimg, FeatimgUploader
  self.per_page = 5
  def self.search(search)
    where("title ILIKE ? OR description ILIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/models/settings.rb
class Settings < ActiveRecord::Base
  mount_uploader :bground, BgroundUploader
  mount_uploader :logo, LogoUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  mount_uploader :avatar, AvatarUploader
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < Clearance::BaseController

  before_filter :redirect_signed_in_users, only: [:create, :new]
  skip_before_filter :require_login, only: [:create, :new]
  skip_before_filter :authorize, only: [:create, :new]

  def new
    @user = user_from_params
    render template: "users/new"
  end

  def create
    @user = user_from_params

    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new"
    end
  end

  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
    email = user_params.delete(:email)
    password = user_params.delete(:password)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
    end
  end

  def user_params
    params[:user] || Hash.new
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.post_id = @post.id
    @comment.save
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to post_path(@post)
    end

  private
  def comment_params
      params.require(:comment).permit(:title, :description, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @blog = Settings.find(1)
    if params[:search]
      @posts = Post.search(params[:search]).paginate(:page => params[:page]).order(created_at: :desc)
    else
      @posts = Post.paginate(:page => params[:page]).order(created_at: :desc)
    end
  end

  def show
    @post = Post.find(params[:id])
    @author = User.find(@post.user_id).name
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    @post.user_id = current_user.id
    @post.save
    redirect_to root_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private
    # Using a private method to encapsulate the permissible parameters is
    # just a good pattern since you'll be able to reuse the same permit
    # list between create and update. Also, you can specialize this method
    # with per-user checking of permissible attributes.
    def post_params
      params.require(:post).permit(:title, :description, :featimg)
    end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  
  def edit
    if Settings.exists? == false
      Settings.create
      @settings = Settings.find(1)
    else
      @settings = Settings.find(1)
    end
  end

  def update
    Settings.update(1, settings_params)
    redirect_to root_path
  end

  private
  def settings_params
      params.require(:settings).permit(:title, :logo, :bground, :facebook, :twitter, :instagram, :youtube, :linkedin, :github)
    end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.update(params[:id], edit_user_params)
    redirect_to edit_user_path
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user).paginate(:page => params[:page]).order(created_at: :desc)
  end

  private

  def edit_user_params
    params.require(:user).permit(:name, :email, :password, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    title = Settings.find(1).title
  end

  def logo
    logo = Settings.find(1).logo.url
  end  

  def background
    background = Settings.find(1).bground.url
  end

  def avatar
    avatar = User.find(params[:id]).avatar.url
  end

  def facebook
    Settings.find(1).facebook
  end

  def twitter
    Settings.find(1).twitter
  end

  def instagram
    Settings.find(1).instagram
  end

  def youtube
    Settings.find(1).youtube
  end

  def linkedin
    Settings.find(1).linkedin
  end

  def github
    Settings.find(1).github
  end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blog/edit.html.erb
<%= form_for :blog do |form| %>
  
    <%= form.label :title %>
    <%= form.text_field :title, type: 'text' %>

    <%= form.label(:logo, :"Upload your logo")  %>
    <%= form.file_field :logo %>

    <%= form.label(:bground, :"Upload your background")  %>
    <%= form.file_field :bground %>

    <p>Social networks (URL please):</p>
    <%= form.label(:facebook, :"Facebook")  %>
    <%= form.text_field :facebook %>
    <%= form.label(:twitter, :"Twitter")  %>
    <%= form.text_field :twitter %>
    <%= form.label(:linkedin, :"LinkedIn")  %>
    <%= form.text_field :linkedin %>
    <%= form.label(:instagram, :"Instagram")  %>
    <%= form.text_field :instagram %>
    <%= form.label(:youtube, :"YouTube")  %>
    <%= form.text_field :youtube %>
    <%= form.label(:github, :"Github")  %>
    <%= form.text_field :github %>

    <div class="submit-field">
      <%= form.submit 'Update' %>
    </div>
  <% end %>

app/views/layouts/_admintop.html.erb
<% if signed_in? %>
  <div class="admin-top">
    <div class="admin-links">
      <%= link_to 'Add a post', new_post_path %>
      <%= link_to 'Blog Settings', settings_path %>
    </div>
    <div class="user-links">
    <% if current_user.avatar.url.blank? == false %>
      <%= link_to image_tag(current_user.avatar.url, :alt => 'User avatar'), edit_user_path(current_user), class:"user-avatar" %>
        <p><%= link_to current_user.name, edit_user_path(current_user), class:"user-name" %></p>
    <% else %>
        <p><%= link_to "User (click to set name/avatar)", edit_user_path(current_user), class:"user-name" %></p>
    <% end %>
      <%= link_to 'Sign out', sign_out_path, method: :delete %>
    </div>
  </div>   
    <% else %>
    <% end %>

app/views/layouts/_footer.erb
<footer>
  <div class="footer">
    <p>© <%= Time.now.strftime("%Y") %> - <%= title %></p>
  </div>
</footer>

app/views/layouts/_navtop.html.erb
<div class="nav-top">
    <div class="nav-links">
    <nav>
      <ul>
        <%= link_to 'Home', root_path %>
        <a href="#"><li>Our Corporate Company</li></a>
        <a href="#"><li>We're hiring</li></a>
        <a href="#"><li>Contact Us</li></a>
        <a href="#"><li>Privacy Policy</li></a>
      </ul>
    </nav>
    </div>
    <div class="social-links">
      <%= render "layouts/social" %>
      <% if not signed_in? %>
        <%= link_to 'Sign in', sign_in_path, class: "sign-in" %>
      <% end %>
    </div>
  </div>

app/views/layouts/_social.html.erb
<% unless facebook.blank? %>
  <%= link_to '<i class="fa fa-facebook-official"></i>'.html_safe, facebook, :target => "_blank", :class => "social" %>
<% end %>

<% unless twitter.blank? %>
  <%= link_to '<i class="fa fa-twitter-square"></i>'.html_safe, twitter, :target => "_blank", :class => "social" %>
<% end %>

<% unless instagram.blank? %>
  <%= link_to '<i class="fa fa-instagram"></i>'.html_safe, instagram, :target => "_blank", :class => "social" %>
<% end %>

<% unless youtube.blank? %>
  <%= link_to '<i class="fa fa-youtube-square"></i>'.html_safe, youtube, :target => "_blank", :class => "social" %>
<% end %>

<% unless linkedin.blank? %>
  <%= link_to '<i class="fa fa-linkedin-square"></i>'.html_safe, linkedin, :target => "_blank", :class => "social" %>
<% end %>

<% unless github.blank? %>
  <%= link_to '<i class="fa fa-github-square"></i>'.html_safe, github, :target => "_blank", :class => "social" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <link href='https://fonts.googleapis.com/css?family=Lora:400,400italic,700,700italic|Istok+Web:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background: url(<%= background %>) no-repeat center center fixed; background-size: cover;">

  <%= render "layouts/admintop" %>
  <%= render "layouts/navtop" %>

  <div class="wrapper">
    <%= yield %>
  </div>

  <%= render "layouts/footer" %>

</body>
</html>

app/views/posts/edit.html.erb
  <div class="main-content">
    <div class="form">
      <p><i class="fa fa-pencil"></i> Edit post</p>
      <%= form_for @post, url: {action: "update"} do |f| %>
        <%= f.label :title, "Post title" %>
        <%= f.text_field :title %>

        <%= f.label :description, "Post content" %>
        <%= f.cktext_area :description %>

        <% if @post.featimg.url.empty? == false %>
          <%= f.label("Current Featured Image")  %>
          <img src="<%= @post.featimg.url %>">
        <% end %>

        <%= f.label :featimg, "Upload New Featured Image" %>
        <%= f.file_field :featimg %>

        <%= f.submit "Update" %>
      <% end %>
      </div>
    </div>
  </div>

app/views/posts/index.html.erb
  <header>
    <div class="branding">
      <img src="<%=@blog.logo.url %>" class="blog-logo" />
    </div>
  </header>
<div class="main-content">
  <div class="search-form">
    <%= form_tag(posts_path, :method => "get") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
      <%= submit_tag "Search" %>
    <% end %>
    <% if @posts.present? == false %>
       <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
    <% end %>
  </div>
  <div class="post">
  <% @posts.each do |post| %>
    <h1><%= link_to post.title, post_path(post) %></h1>
    <% if signed_in? && post.user_id == current_user.id %>
      <div class="author-options">
        <%= link_to '<i class="fa fa-pencil"> Edit</i>'.html_safe, edit_post_path(post) %>
        <%= link_to '<i class="fa fa-times"> Delete</i>'.html_safe, post_path(post), method: "delete" %>
      </div>
    <% end %>
    <img src="<%= post.featimg.url %>">
    <p><%= raw post.description.truncate(300) %></p>
    <p><%= link_to "Read more...", post_path(post), class:"read-more" %></p>
    <div class="post-info">
      <p class="time"><i class="fa fa-calendar"></i>Posted on: <%= post.created_at.strftime("%A, %d %B %Y") %></p>
      <p class="author"><i class="fa fa-user"></i>Written by:&nbsp; <%= link_to User.find(post.user_id).name, user_path(User.find(post.user_id)) %> <%= link_to image_tag(User.find(post.user_id).avatar.url, :alt => 'User avatar', class: "user-avatar"), user_path(User.find(post.user_id)) %> </p>
    </div>
    <hr>
    <% end %>
    <%= will_paginate @posts %>
  </div>
</div>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>

app/views/posts/new.html.erb
<div class="main-content">
<div class="form">
  <p><i class="fa fa-plus-square"></i> Add a Post</p>
      <%= form_for @post, url: {action: "create"} do |f| %>
        <%= f.label :title, "Post title" %>
        <%= f.text_field :title %>
        <%= f.label :description, "Post content" %>
        <%= f.cktext_area :description %>
        <%= f.label :featimg, "Add a featured image" %>
        <%= f.file_field :featimg %>
        <%= f.submit "Create" %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main-content">
  <div class="post">
    <h1><%= @post.title %></h1>
    <img src="<%= @post.featimg.url %>" />
      <% if signed_in? && @post.user_id == current_user.id %>
          <div class="author-options">
            <%= link_to '<i class="fa fa-pencil"> Edit</i>'.html_safe, edit_post_path(@post) %>
            <%= link_to '<i class="fa fa-times"> Delete</i>'.html_safe, post_path(@post), method: "delete" %>
          </div>
      <% end %>
       <p><%= raw @post.description %></p>
     <div class="post-info">
      <p class="time"><i class="fa fa-calendar"></i>Posted on: <%= @post.created_at.strftime("%A, %d %B %Y") %></p>
      <p class="author"><i class="fa fa-user"></i>Written by:&nbsp; <%= link_to User.find(@post.user_id).name, user_path(User.find(@post.user_id)) %> <%= link_to image_tag(User.find(@post.user_id).avatar.url, :alt => 'User avatar', class: "user-avatar"), user_path(User.find(@post.user_id)) %></p>
    </div>
    <hr>
  </div>
  <div class="comments">
    <h1>Comments</h1>
    <% @post.comments.each do |comment| %>
      <p><%= comment.comment %></p>
      <p class="comment-data">By <%= comment.name %>, on <%= comment.created_at.strftime("%A, %d %B %Y") %></p>
      <% if signed_in? && @post.user_id == current_user.id %>
                <%= link_to '<i class="fa fa-times"> Delete</i>'.html_safe, post_comment_path(params[:id], comment), method: "delete" %>
        <% end %>
    <% end %>
  </div>
    <div class="form">
    <p><i class="fa fa-pencil-square-o"></i> Leave a comment</p>
    <%= form_for @comment, url: post_comments_path(post_id: @post.id) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :comment %>
      <%= f.text_area :comment, size: "60x12" %>
      <%= f.submit "Create" %>
    <% end %>
    </div>
</div>

app/views/settings/edit.html.erb
<div class="main-content">
<div class="form">
<p><i class="fa fa-wrench"></i> Blog Settings</p>
    <%= form_for @settings, url: {action: "update"} do |form| %>
      
        <%= form.label :title %>
        <%= form.text_field :title, type: 'text' %>

        <% if logo.blank? == false %>
            <%= form.label(:"Current logo") %>
            <img src="<%= logo %>">
        <% end %>

        <%= form.label(:logo, :"Upload a new logo")  %>
        <%= form.file_field :logo %>

         <% if background.blank? == false %>
            <%= form.label(:"Current background") %>
            <img src="<%= background %>">
        <% end %>

        <%= form.label(:bground, :"Upload a new background")  %>
        <%= form.file_field :bground %>

        <div class="submit-field">
          <%= form.submit 'Update' %>
        </div>
    <% end %>
    </div>
    <hr>
    <div class="form">
        <p><i class="fa fa-users"></i> Social networks (URL please):</p>
        <%= form_for @settings, url: {action: "update"} do |form| %>
            <%= form.label(:facebook, :"Facebook")  %>
            <%= form.text_field :facebook %>
            <%= form.label(:twitter, :"Twitter")  %>
            <%= form.text_field :twitter %>
            <%= form.label(:linkedin, :"LinkedIn")  %>
            <%= form.text_field :linkedin %>
            <%= form.label(:instagram, :"Instagram")  %>
            <%= form.text_field :instagram %>
            <%= form.label(:youtube, :"YouTube")  %>
            <%= form.text_field :youtube %>
            <%= form.label(:github, :"Github")  %>
            <%= form.text_field :github %>
            <%= form.submit 'Update' %>
        <% end %>
        </div>
    </div>
</div>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div><br>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div><br>

app/views/users/edit.html.erb
  <div class="main-content">
    <div class="form">
      <p><i class="fa fa-user"></i> User Settings</p>
      <%= form_for @user do |form| %>
        <%= render partial: '/users/form', object: form %>

        <%= form.label :name %>
        <%= form.text_field :name, type: 'text' %>

        <% if current_user.avatar.url.blank? == false %>
          <%= form.label("Current avatar")  %>
          <img src="<%= current_user.avatar.url %>">
        <% end %>

        <%= form.label(:avatar, :"Upload a new avatar")  %>
        <%= form.file_field :avatar %> <br>

        <%= form.submit 'Update' %>
      
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
  <div class="main-content">
    <div class="form">
      <p><%= t(".title") %></p>

      <%= form_for @user do |form| %>
        <%= render partial: '/users/form', object: form %>

          <%= form.submit %>

      <% end %>  
    </div>
    <hr>
    <%= link_to t(".sign_in"), sign_in_path %>
 </div>

app/views/users/show.html.erb
    <header>
      <div class="branding">
        <img src="<%= logo %>" class="blog-logo" />
      </div>
    </header>
  <div class="main-content">
    <div class="author-profile">
      <img src="<%= avatar %>" />
      <h1><%= @user.name %></h1>
      <h2><%= @user.email %></h2>
    </div>
    <div class="post">
    <% @posts.each do |post| %>
      <h1><%= link_to post.title, post_path(post) %></h1>
      <% if signed_in? && post.user_id == current_user.id %>
        <div class="author-options">
          <%= link_to '<i class="fa fa-pencil"> Edit</i>'.html_safe, edit_post_path(post) %>
          <%= link_to '<i class="fa fa-times"> Delete</i>'.html_safe, post_path(post), method: "delete" %>
        </div>
      <% end %>
      <img src="<%= post.featimg.url %>">
      <p><%= truncate(post.description.html_safe, :length => 300) %></p>
      <p><%= link_to "Read more...", post_path(post), class:"read-more" %></p>
      <div class="post-info">
        <p class="time"><i class="fa fa-calendar"></i>Posted on: <%= post.created_at.strftime("%A, %d %B %Y") %></p>
        <p class="author"><i class="fa fa-user"></i>Written by: <%= @user.name %> <%= image_tag(@user.avatar.url, :alt => 'User avatar', class: "user-avatar") %> </p>
      </div>
      <hr>
      <% end %>
      <%= will_paginate @posts %>
    </div>
  </div>